.TH "/home/cheneby/love/hekate/src/utils Directory Reference" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/src/utils Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmatrix\&.lua\fP"
.br
.ti -1c
.RI "file \fButils\&.lua\fP"
.br
.in -1c
