.TH "/home/cheneby/love/hekate/src Directory Reference" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcontroller\&.lua\fP"
.br
.ti -1c
.RI "file \fBgraphics\&.lua\fP"
.br
.ti -1c
.RI "file \fBresource\&.lua\fP"
.br
.ti -1c
.RI "file \fBworld\&.lua\fP"
.br
.in -1c
