.TH "/home/cheneby/love/hekate/resource/component Directory Reference" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/resource/component Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcamera\&.lua\fP"
.br
.ti -1c
.RI "file \fBplayer\&.lua\fP"
.br
.ti -1c
.RI "file \fBposition\&.lua\fP"
.br
.ti -1c
.RI "file \fBrenderer\&.lua\fP"
.br
.ti -1c
.RI "file \fBtilemap\&.lua\fP"
.br
.in -1c
