.TH "/home/cheneby/love/hekate/resource/component/camera.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/resource/component/camera.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBCamera\fP \fBload\fP ()"
.br
.ti -1c
.RI "function \fBCamera\fP \fBmousepressed\fP (x, y, button)"
.br
.ti -1c
.RI "function \fBCamera\fP \fBupdate\fP (dt)"
.br
.ti -1c
.RI "function \fBCamera\fP \fBdraw\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fBcontroller\fP = require 'src/controller'"
.br
.ti -1c
.RI "local \fBgraphics\fP = require 'src/graphics'"
.br
.ti -1c
.RI "local \fButils\fP = require 'src/utils/utils'"
.br
.ti -1c
.RI "local \fBdraw_depth\fP = function()"
.br
.ti -1c
.RI "local \fBCamera\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fBCamera\fP draw ()"

.SS "function \fBCamera\fP load ()"

.SS "function \fBCamera\fP mousepressed (x, y, button)"

.SS "function \fBCamera\fP update (dt)"

.SH "Variable Documentation"
.PP 
.SS "local Camera = {}"

.SS "local controller = require 'src/controller'"

.SS "local draw_depth = function()"

.SS "local graphics = require 'src/graphics'"

.SS "local utils = require 'src/utils/utils'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
