.TH "/home/cheneby/love/hekate/conf.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/conf.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function love \fBconf\fP (t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function love conf (t)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
