.TH "/home/cheneby/love/hekate/src/graphics.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/src/graphics.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fBtile_size\fP = 32"
.br
.ti -1c
.RI "local \fBget_quads\fP = function(tileset)"
.br
.RI "\fIUse to get the quads of a specific tileset\&. \fP"
.ti -1c
.RI "local \fBdraw_tilemap\fP = function(tilemap, tileset)"
.br
.RI "\fIUse to draw a tilemap given a tileset\&. \fP"
.ti -1c
.RI "local \fBdebug\fP = function()"
.br
.RI "\fIDebug draw some stuffs in a top bar\&. \fP"
.ti -1c
.RI "\fBreturn\fP {\fBtile_size\fP = \fBtile_size\fP"
.br
.RI "\fIThe singleton interface that could be accessed from everywhere\&. \fP"
.in -1c
.SH "Variable Documentation"
.PP 
.SS "debug = function()"

.PP
Debug draw some stuffs in a top bar\&. 
.SS "draw_tilemap = function(tilemap, tileset)"

.PP
Use to draw a tilemap given a tileset\&. 
.SS "get_quads = function(tileset)"

.PP
Use to get the quads of a specific tileset\&. 
.SS "return {\fBtile_size\fP = \fBtile_size\fP"

.PP
The singleton interface that could be accessed from everywhere\&. 
.SS "local tile_size = 32"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
