.TH "/home/cheneby/love/hekate/resource/component/player.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/resource/component/player.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBPlayer\fP \fBkeypressed\fP (key)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fBworld\fP = require 'src/world'"
.br
.ti -1c
.RI "local \fBPlayer\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fBPlayer\fP keypressed (key)"

.SH "Variable Documentation"
.PP 
.SS "local Player = {}"

.SS "local world = require 'src/world'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
