.TH "/home/cheneby/love/hekate/resource/component/position.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/resource/component/position.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBPosition\fP \fBto_pixel\fP ()"
.br
.ti -1c
.RI "function \fBPosition\fP \fBmove\fP (x, y)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fBcontroller\fP = require 'src/controller'"
.br
.ti -1c
.RI "local \fBgraphics\fP = require 'src/graphics'"
.br
.ti -1c
.RI "local \fBPosition\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fBPosition\fP move (x, y)"

.SS "function \fBPosition\fP to_pixel ()"

.SH "Variable Documentation"
.PP 
.SS "local controller = require 'src/controller'"

.SS "local graphics = require 'src/graphics'"

.SS "local Position = {}"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
