.TH "/home/cheneby/love/hekate/resource/component/renderer.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/resource/component/renderer.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBRenderer\fP \fBload\fP ()"
.br
.ti -1c
.RI "function \fBRenderer\fP \fBupdate\fP (dt)"
.br
.ti -1c
.RI "function \fBRenderer\fP \fBrender\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fBgraphics\fP = require 'src/graphics'"
.br
.ti -1c
.RI "local \fBresource\fP = require 'src/resource'"
.br
.ti -1c
.RI "local \fButils\fP = require 'src/utils/utils'"
.br
.ti -1c
.RI "local \fBworld\fP = require 'src/world'"
.br
.ti -1c
.RI "local \fBRenderer\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fBRenderer\fP load ()"

.SS "function \fBRenderer\fP render ()"

.SS "function \fBRenderer\fP update (dt)"

.SH "Variable Documentation"
.PP 
.SS "local graphics = require 'src/graphics'"

.SS "local Renderer = {}"

.SS "local resource = require 'src/resource'"

.SS "local utils = require 'src/utils/utils'"

.SS "local world = require 'src/world'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
