.TH "/home/cheneby/love/hekate/src/resource.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/src/resource.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fBgraphics\fP = require 'src/graphics'"
.br
.RI "\fIImport graphics methods\&. \fP"
.ti -1c
.RI "local \fBresources\fP = {}"
.br
.RI "\fIThe list of all resources to fetch\&. \fP"
.ti -1c
.RI "local \fBload_snippet\fP = function(file_path)"
.br
.RI "\fIShort function to load a snippet with its file path\&. \fP"
.ti -1c
.RI "local \fBload_tileset\fP = function(file_path)"
.br
.RI "\fIShort function to load a tileset with its file path\&. \fP"
.ti -1c
.RI "local \fBload_type\fP = function(type, \fBload\fP)"
.br
.RI "\fIUse to load a specific type of resource folder\&. \fP"
.ti -1c
.RI "local \fBload\fP = function()"
.br
.RI "\fIAutomatically load all the resources folders\&. \fP"
.ti -1c
.RI "local \fBget\fP = function(type, name)"
.br
.RI "\fIReturn a specific resource\&. \fP"
.ti -1c
.RI "\fBreturn\fP {\fBload\fP = \fBload\fP"
.br
.RI "\fIThe singleton interface that could be accessed from everywhere\&. \fP"
.in -1c
.SH "Variable Documentation"
.PP 
.SS "get = function(type, name)"

.PP
Return a specific resource\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP string: type of resources asked 
.br
\fIname\fP string: name of the resource 
.RE
.PP
\fBReturns:\fP
.RS 4
table: key = name, value = Image 
.RE
.PP

.SS "local graphics = require 'src/graphics'"

.PP
Import graphics methods\&. 
.SS "local load = function()"

.PP
Automatically load all the resources folders\&. 
.SS "local load_snippet = function(file_path)"

.PP
Short function to load a snippet with its file path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile_path\fP string: path to file 
.RE
.PP
\fBReturns:\fP
.RS 4
table: key = name, value = code for object 
.RE
.PP

.SS "local load_tileset = function(file_path)"

.PP
Short function to load a tileset with its file path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile_path\fP string: path to file 
.RE
.PP
\fBReturns:\fP
.RS 4
table: key = loaded Image, value = Quad 
.RE
.PP

.SS "local load_type = function(type, \fBload\fP)"

.PP
Use to load a specific type of resource folder\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP string: type of resources asked 
.br
\fIfunction\fP function used to load resource into a table 
.RE
.PP
\fBReturns:\fP
.RS 4
table: key = name, value = Image 
.RE
.PP

.SS "local resources = {}"

.PP
The list of all resources to fetch\&. 
.SS "return {\fBload\fP = \fBload\fP"

.PP
The singleton interface that could be accessed from everywhere\&. 
.PP
\fBReturns:\fP
.RS 4
load 
.PP
get 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
