.TH "/home/cheneby/love/hekate/src/utils/utils.lua" 3 "Thu May 17 2018" "Hekate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cheneby/love/hekate/src/utils/utils.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fButils\fP \fBread_file\fP (file_path)"
.br
.RI "\fIRead a file and return a string\&. \fP"
.ti -1c
.RI "function \fButils\fP \fBread_table\fP (file_path)"
.br
.RI "\fIRead a lua-like file and return its table\&. \fP"
.ti -1c
.RI "function \fButils\fP \fBpack\fP (\&.\&.\&.)"
.br
.RI "\fIPack arguments into a table\&. \fP"
.ti -1c
.RI "function \fButils\fP \fBlerp\fP (a, b, t, s)"
.br
.ti -1c
.RI "function \fButils\fP \fBinput_axe\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "local \fButils\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fButils\fP input_axe ()"

.SS "function \fButils\fP lerp (a, b, t, s)"

.SS "function \fButils\fP pack (\&.\&.\&.)"

.PP
Pack arguments into a table\&. 
.SS "function \fButils\fP read_file (file_path)"

.PP
Read a file and return a string\&. 
.SS "function \fButils\fP read_table (file_path)"

.PP
Read a lua-like file and return its table\&. 
.SH "Variable Documentation"
.PP 
.SS "local utils = {}"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hekate from the source code\&.
